### ISSUE TITLE
Due date for Milestone #1?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-uploader#10]
@rabernat , I'm just wondering when this work is scheduled to occur (or be done by)

Is there a due date in mind for [Milestone #1 (v0.1.0)](https://github.com/pangeo-data/pangeo-cloud-uploader/milestones)  (I'm guessing you meant v 0.1.0, not 0.0.1)

**Comment by rabernat** [comment]
The interns haven't even been hired yet, so there won't be much action here
for a while.

However, you can already serialze data to zarr stores directly using the
`xarray.Dataset.to_zarr` method. @mrocklin has suggested that this whole
project might be overkill, since that already works pretty well.

**Comment by kaipak** [comment]
I've been assigned to work on some tasks noted on this issue, although the goal of making an explicit command line tool may be on hold for the moment. I'm sifting through required work on this and related work. I should have more concrete updates in the next week.

**Comment by rsignell-usgs** [comment]
I've got a 2.4GB netcdf file that I'd like to experiment on.  What's the best way to make it accessible to pangeo?

**Comment by rsignell-usgs** [comment]
@kaipak or @rabernat, any updates?
